"""initial schema

Revision ID: 4f3d9b8f7f5e
Revises: 
Create Date: 2026-09-09 12:01:28.105249+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '4f3d9b8f7f5e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.Enum('user', 'moderator', 'admin', 'superadmin', name='user_role', native_enum=False, create_constraint=True, length=32), server_default='user', nullable=False),
    sa.Column('tz', sa.String(length=64), server_default='Europe/Moscow', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_users_tg_id'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String(length=256)), server_default='{}', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('active', 'hidden', 'pending_moderation', name='book_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('dedup_key', sa.String(length=512), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('fk_books_added_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('dedup_key', name='uq_books_dedup_key')
    )
    op.create_index('ix_books_title_trgm', 'books', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('uq_books_isbn13', 'books', ['isbn13'], unique=True, postgresql_where=sa.text('isbn13 IS NOT NULL'))
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_reading', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'hidden', name='event_type_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_event_types_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_types')),
    sa.UniqueConstraint('slug', name=op.f('uq_event_types_slug'))
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='friendship_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_user_id <> to_user_id', name=op.f('ck_friendships_no_self_friendship')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_friendships_from_user_id_users')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_friendships_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendships')),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_from_user_id'), 'friendships', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_friendships_to_user_id'), 'friendships', ['to_user_id'], unique=False)
    op.create_table('meeting_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('free', 'busy', 'disabled', name='room_status', native_enum=False, create_constraint=True, length=32), server_default='free', nullable=False),
    sa.Column('current_application_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_meeting_rooms_added_by_users')),
    sa.ForeignKeyConstraint(['current_application_id'], ['organizer_applications.id'], name=op.f('fk_meeting_rooms_current_application_id_organizer_applications'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_rooms')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_meeting_rooms_chat_id'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('demand_threshold', 'application_submitted', 'application_chat_open', 'application_approved', 'application_rejected', 'no_free_room', 'slot_voting_open', 'event_scheduled', 'event_changed', 'event_cancelled', 'reminder_24h', 'reminder_2h', 'low_attendance', 'feedback_request', 'friend_request', 'friend_accepted', 'role_granted', 'book_request_decided', name='notification_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedup_key', name='uq_notifications_dedup_key')
    )
    op.create_index('ix_notifications_user_unsent', 'notifications', ['user_id', 'sent_at'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_kind', sa.Enum('student', 'applicant', 'staff', 'guest', name='member_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('faculty', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('university_email', sa.String(length=255), nullable=True),
    sa.Column('reading_pace', sa.Enum('rare', 'steady', 'fast', name='reading_pace', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('club_experience', sa.Enum('none', 'visitor', 'organizer', name='club_experience', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('book_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String(length=256)), server_default='{}', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='book_request_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_requests_book_id_books')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_book_requests_reviewed_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_book_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_requests'))
    )
    op.create_index(op.f('ix_book_requests_user_id'), 'book_requests', ['user_id'], unique=False)
    op.create_table('book_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('google_books', 'open_library', 'manual', name='book_source_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_sources_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_sources')),
    sa.UniqueConstraint('source', 'external_id', name='uq_book_source_external')
    )
    op.create_index(op.f('ix_book_sources_book_id'), 'book_sources', ['book_id'], unique=False)
    op.create_table('demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('has_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Enum('manual', 'scheduled', name='demand_revoke_reason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_demands_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_demands_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demands'))
    )
    op.create_index(op.f('ix_demands_book_id'), 'demands', ['book_id'], unique=False)
    op.create_index(op.f('ix_demands_user_id'), 'demands', ['user_id'], unique=False)
    op.create_index('uq_demand_active', 'demands', ['user_id', 'book_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('organizer_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('proposed_type_title', sa.String(length=128), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('submitted', 'chat_open', 'approved', 'rejected', 'withdrawn', name='application_status', native_enum=False, create_constraint=True, length=32), server_default='submitted', nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('invite_link', sa.String(length=512), nullable=True),
    sa.Column('chat_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audience', postgresql.ARRAY(sa.String(length=16)), server_default='{}', nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_organizer_applications_book_id_books')),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_organizer_applications_event_type_id_event_types')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_organizer_applications_reviewed_by_users')),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_rooms.id'], name=op.f('fk_organizer_applications_room_id_meeting_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organizer_applications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizer_applications'))
    )
    op.create_index(op.f('ix_organizer_applications_book_id'), 'organizer_applications', ['book_id'], unique=False)
    op.create_index(op.f('ix_organizer_applications_user_id'), 'organizer_applications', ['user_id'], unique=False)
    op.create_index('uq_application_open', 'organizer_applications', ['user_id', 'book_id'], unique=True, postgresql_where=sa.text("status IN ('submitted', 'chat_open')"))
    op.create_table('profile_event_types',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_profile_event_types_event_type_id_event_types')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.user_id'], name=op.f('fk_profile_event_types_profile_id_profiles')),
    sa.PrimaryKeyConstraint('profile_id', 'event_type_id', name=op.f('pk_profile_event_types'))
    )
    op.create_table('reading_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('want_to_read', 'reading', 'finished', 'abandoned', name='reading_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('finished_on', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 1 AND 10', name=op.f('ck_reading_entries_score_range')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_entries_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_entries')),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_reading_entry')
    )
    op.create_index(op.f('ix_reading_entries_book_id'), 'reading_entries', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_entries_user_id'), 'reading_entries', ['user_id'], unique=False)
    op.create_table('room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_rooms.id'], name=op.f('fk_room_messages_room_id_meeting_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_messages')),
    sa.UniqueConstraint('room_id', 'message_id', name='uq_room_message')
    )
    op.create_index(op.f('ix_room_messages_room_id'), 'room_messages', ['room_id'], unique=False)
    op.create_table('demand_types',
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], name=op.f('fk_demand_types_demand_id_demands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_demand_types_event_type_id_event_types')),
    sa.PrimaryKeyConstraint('demand_id', 'event_type_id', name=op.f('pk_demand_types'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('min_attendance', sa.Integer(), nullable=True),
    sa.Column('audience', postgresql.ARRAY(sa.String(length=16)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('slot_selection', 'voting', 'scheduled', 'held', 'cancelled', name='event_status', native_enum=False, create_constraint=True, length=32), server_default='slot_selection', nullable=False),
    sa.Column('vote_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Enum('auto', 'organizer', 'admin', name='decided_by', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('attendance_code', sa.String(length=8), nullable=True),
    sa.Column('code_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['organizer_applications.id'], name=op.f('fk_events_application_id_organizer_applications')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_events_book_id_books')),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_events_event_type_id_event_types')),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.id'], name=op.f('fk_events_organizer_user_id_users')),
    sa.ForeignKeyConstraint(['slot_id'], ['event_slots.id'], name='fk_events_slot_id_event_slots', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_book_id'), 'events', ['book_id'], unique=False)
    op.create_index(op.f('ix_events_organizer_user_id'), 'events', ['organizer_user_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('code', 'manual', name='attendance_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_attendance_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_attendance_marked_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_attendance')
    )
    op.create_index(op.f('ix_attendance_event_id'), 'attendance', ['event_id'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_table('event_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 1 AND 10', name=op.f('ck_event_feedback_feedback_score_range')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_feedback_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_feedback')),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_feedback')
    )
    op.create_index(op.f('ix_event_feedback_event_id'), 'event_feedback', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_feedback_user_id'), 'event_feedback', ['user_id'], unique=False)
    op.create_table('event_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='120', nullable=False),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_slots_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_slots'))
    )
    op.create_index(op.f('ix_event_slots_event_id'), 'event_slots', ['event_id'], unique=False)
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('going', 'maybe', 'declined', 'waitlist', name='participation_state', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_participations_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participations')),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_participation')
    )
    op.create_index(op.f('ix_participations_event_id'), 'participations', ['event_id'], unique=False)
    op.create_index(op.f('ix_participations_user_id'), 'participations', ['user_id'], unique=False)
    op.create_table('slot_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_slot_votes_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['event_slots.id'], name=op.f('fk_slot_votes_slot_id_event_slots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_slot_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_votes')),
    sa.UniqueConstraint('slot_id', 'user_id', name='uq_slot_vote')
    )
    op.create_index(op.f('ix_slot_votes_event_id'), 'slot_votes', ['event_id'], unique=False)
    op.create_index(op.f('ix_slot_votes_slot_id'), 'slot_votes', ['slot_id'], unique=False)
    op.create_index(op.f('ix_slot_votes_user_id'), 'slot_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_votes_user_id'), table_name='slot_votes')
    op.drop_index(op.f('ix_slot_votes_slot_id'), table_name='slot_votes')
    op.drop_index(op.f('ix_slot_votes_event_id'), table_name='slot_votes')
    op.drop_table('slot_votes')
    op.drop_index(op.f('ix_participations_user_id'), table_name='participations')
    op.drop_index(op.f('ix_participations_event_id'), table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_event_slots_event_id'), table_name='event_slots')
    op.drop_table('event_slots')
    op.drop_index(op.f('ix_event_feedback_user_id'), table_name='event_feedback')
    op.drop_index(op.f('ix_event_feedback_event_id'), table_name='event_feedback')
    op.drop_table('event_feedback')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_event_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_events_organizer_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_book_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('demand_types')
    op.drop_index(op.f('ix_room_messages_room_id'), table_name='room_messages')
    op.drop_table('room_messages')
    op.drop_index(op.f('ix_reading_entries_user_id'), table_name='reading_entries')
    op.drop_index(op.f('ix_reading_entries_book_id'), table_name='reading_entries')
    op.drop_table('reading_entries')
    op.drop_table('profile_event_types')
    op.drop_index('uq_application_open', table_name='organizer_applications', postgresql_where=sa.text("status IN ('submitted', 'chat_open')"))
    op.drop_index(op.f('ix_organizer_applications_user_id'), table_name='organizer_applications')
    op.drop_index(op.f('ix_organizer_applications_book_id'), table_name='organizer_applications')
    op.drop_table('organizer_applications')
    op.drop_index('uq_demand_active', table_name='demands', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_demands_user_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_book_id'), table_name='demands')
    op.drop_table('demands')
    op.drop_index(op.f('ix_book_sources_book_id'), table_name='book_sources')
    op.drop_table('book_sources')
    op.drop_index(op.f('ix_book_requests_user_id'), table_name='book_requests')
    op.drop_table('book_requests')
    op.drop_table('settings')
    op.drop_table('profiles')
    op.drop_index('ix_notifications_user_unsent', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('meeting_rooms')
    op.drop_index(op.f('ix_friendships_to_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_from_user_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_table('event_types')
    op.drop_index('uq_books_isbn13', table_name='books', postgresql_where=sa.text('isbn13 IS NOT NULL'))
    op.drop_index('ix_books_title_trgm', table_name='books', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_table('books')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
