"""world ratings on books

Средняя оценка и число голосов во внешних источниках. Нужны для сортировки
каталога по мировой известности: своих оценок в клубе поначалу почти нет,
и сортировать по ним нечего.

Revision ID: 9f94e344b7bb
Revises: 7d6674527ccd
Create Date: 2026-09-10 21:00:38.175720+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9f94e344b7bb'
down_revision: str | None = '7d6674527ccd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('world_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('world_ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'world_ratings_count')
    op.drop_column('books', 'world_rating')
    # ### end Alembic commands ###
